Entity Framework/Controllers/HeroeController.cs
using System.Collections.Generic;
using System.Linq;

using Entity_Framework.Database;
using Entity_Framework.Models;
using Entity_Framework.Models.ViewModel;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Entity_Framework.Controllers {
    public class HeroeController : Controller {
        private HeroeDbContext _heroeDbContext;
        public HeroeController (HeroeDbContext heroeDbContext) {
            this._heroeDbContext = heroeDbContext;
        }

        [HttpGet]
        public IActionResult Create() {
            return View (getCrearHeroeViewModel());
        }

        [HttpPost]
        public IActionResult Create (CrearHeroeViewModel heroeVm) {
                            
            if (ModelState.IsValid) {
                var imagenes = new List<Imagen> {
                    new Imagen {
                    Url = heroeVm.Imagen,
                    Orden = heroeVm.OrdenImagen
                    }
                };

                var universoSeleccionado = _heroeDbContext.Universos
                                            .Where(x => x.Id == heroeVm.Universo)
                                            .FirstOrDefault();

                var heroe = new Heroe {
                    Nombre = heroeVm.Nombre,
                    Descripcion = heroeVm.Descripcion,
                    Imagenes = imagenes,
                    Universo = universoSeleccionado
                };

                _heroeDbContext.Heroes.Add(heroe);
                _heroeDbContext.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            return View(getCrearHeroeViewModel());
        }

        public IActionResult GetAll() {
            var heroesComplete = _heroeDbContext.Heroes
                .Include(x => x.Imagenes)
                .Include(x => x.Universo)
                .ToList();

            var heroes = heroesComplete.Select(x => new GaleriaViewModel {
                IdHeroe = x.Id, 
                Nombre = x.Nombre,
                Descripcion = x.Descripcion, 
                Imagen = x.Imagenes.FirstOrDefault().Url
            }).ToList();  

            return View(heroes);
        }

        private CrearHeroeViewModel getCrearHeroeViewModel() {
             var universos = _heroeDbContext.Universos
                .Select (x => new SelectListItem {
                    Text = x.Nombre,
                    Value = x.Id.ToString()
                })
                .ToList();

            return new CrearHeroeViewModel {
                Universos = universos
            };
        }
    }
}

Entity Framework/Controllers/UsuarioController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Text;
using Entity_Framework.Database;
using Entity_Framework.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Entity_Framework.Controllers
{
    public class UsuarioController : Controller
    {
        private HeroeDbContext _heroeDbContex;
 
        public UsuarioController(HeroeDbContext heroeDbContex)
        {
            _heroeDbContex = heroeDbContex;
        }

        public IActionResult CrearUsuario() {
            string pass = "javier1234";
                var usuario = new Usuario {
                    Nombre = "Javi", 
                    User = "javi",
                    Contraseña = Encoding.UTF8.GetBytes(pass),
                    Rol = Rol.Administrador,
                };
                _heroeDbContex .Add(usuario);
                _heroeDbContex .SaveChanges();
                return Json("ok");
        }
        
        [HttpGet]
        public IActionResult Ingresar(string returnUrl) {
            TempData["UrlIngreso"] = returnUrl;
            return View();
        }

        [HttpPost]
        public IActionResult Ingresar(string usuario, string pass) {

            // Validamos que hayan ingresado el usuario y contraseña
            if (!string.IsNullOrEmpty(usuario) && !string.IsNullOrEmpty(pass)) {
                // Verificamos que exista el usuario
                var user =  _heroeDbContex.Usuarios.FirstOrDefault(u => u.User == usuario);
                if (user != null) {
                    // Validamos que coincida la contraseña
                    var contraseña = Encoding.UTF8.GetBytes(pass);

                    if (contraseña.SequenceEqual(user.Contraseña)) {

                        // Creamos los Claims (credencial de acceso con informacion del usuario)
                        ClaimsIdentity identidad = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

                        // Agregamos a la credencial el nombre de usuario
                        identidad.AddClaim(new Claim(ClaimTypes.Name, usuario));
                        // Agregamos a la credencial el nombre del estudiante/administrador
                        identidad.AddClaim(new Claim(ClaimTypes.GivenName, user.Nombre));
                        // Agregamos a la credencial el Rol
                        identidad.AddClaim(new Claim(ClaimTypes.Role, user.Rol.ToString()));

                        ClaimsPrincipal principal = new ClaimsPrincipal(identidad);

                        // Ejecutamos el Login
                        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                                             
                        // Redirigimos a la pagina principal
                        return RedirectToAction("Index", "Home");
                    }                    
                }
            }

            ViewBag.ErrorEnLogin = "Verifique el usuario y contraseña";
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Salir()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult AccesoDenegado()
        {
            return View();
        }

    }
}

Entity Framework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Heroes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Entity_Framework</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Heroe" asp-action="GetAll">Galeria</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Heroe" asp-action="Create">Crear Heroe</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item float-right">
                                <a class="nav-link text-success font-italic" asp-area="">@User.FindFirstValue(ClaimTypes.GivenName)</a>
                            </li>
                            <li class="nav-item float-right">
                                <form asp-controller="Usuario" asp-action="Salir" method="post">
                                    <button type="submit" class="nav-link text-danger">Salir</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-warning border border-primary bg-light" asp-area="" asp-controller="Usuario" asp-action="Ingresar">Ingresar</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVC_Entity_Framework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Entity Framework/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fondo-error.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>