MVC-NT1/Models/ErrorViewModel.cs
using System;

namespace MVC_NT1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC-NT1/Models/OrderViewModel.cs
namespace MVC_NT1.Models
{
    public class OrderViewModel
    {
        public int Id { get; set; }
        
        
        public string Name { get; set; }

        public double Total { get; set; }
        
    }
}

MVC-NT1/Models/UsuarioViewModel.cs
namespace MVC_NT1.Models
{
    public class UsuarioViewModel
    {
        public string Nombre { get; set; }

        public string Email { get; set; }
    }
}

MVC-NT1/Controllers/OrderController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

using MVC_NT1.Models;

namespace MVC_NT1.Controllers {
    public class OrderController : Controller {
       
        //En este ejemplo vemos hacer un redirect a otra vista
        public IActionResult EjemploRedirectAOtraView() {
            return View ("Views/Home/Privacy.cshtml");
        }

        //Enseñar definición del viewmodel (https://docs.microsoft.com/es-es/aspnet/core/mvc/views/overview?view=aspnetcore-5.0)
        //Explicar que en una vista se le puede pasar solo un model(salvo que uses vistas parciales, etc) por eso son muy útiles los ViewModel
        // Ver como pasar un model de la vista al controller
        public IActionResult NewOrder() {
            var orderViewModel = new OrderViewModel {
                Id = 1,
                Name = "Javi",
                Total = 10
            };

            return View();
        }

        //Ejemplo de como recorrer una lista y como usar el @ para codigo en las vistas
        public IActionResult OrderList() {
            var orderListViewModel = new List<OrderViewModel> {
                new OrderViewModel {
                Id = 1,
                Name = "Javi",
                Total = 10
                },
                new OrderViewModel {
                Id = 2,
                Name = "Pedro",
                Total = 20
                },
            };

            return View (orderListViewModel);
        }
    }
}

MVC-NT1/Controllers/PrimerosPasosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVC_NT1.Controllers
{
    public class PrimerosPasosController : Controller
    {
        //https://localhost:5001/PrimerosPasos/getNombre?name=juan&apellido=pedro
        public string getNombre(string name, string apellido) {
            return $"Su nombre es: {name} y su apellido {apellido}";
        }   
    }
}

MVC-NT1/Controllers/RegistroController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_NT1.Models;

namespace MVC_NT1.Controllers
{
    public class RegistroController : Controller
    {
        [HttpGet]
        public IActionResult RegistrarUsuario() {
            return View();
        }
            
        [HttpPost]
        public IActionResult RegistrarUsuario(UsuarioViewModel user) {
            return View(user);
        }
    }
}

MVC-NT1/Controllers/ViewBagYViewDataController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_NT1.Models;

namespace MVC_NT1.Controllers
{
    public class ViewBagYViewDataController : Controller
    {
        //En este ejemplo vemos como pasar un view data a la vista
        public IActionResult EjemploViewData() {
            ViewData["Message"] = "Este es un mensaje pasado por ViewData";
            ViewBag.Nombe = "Javi";

            var order = new OrderViewModel
            {
                Id = 1, 
                Name = "Javi", 
                Total = 100
            };

            ViewData["order"] = order;
            ViewBag.Order = order;
            return View();
        }
        /*
        ViewData es un objeto de diccionario fuertemente tipado en el que se introducen 
        los datos a través de la conocida sintaxis "key/value".
        ViewData deriva de la clase ViewDataDictionary.
        Uso y asignación al objetos: ViewData["Message"]= "Este es un mensaje pasado por ViewData"
        Lectura del objeto en la vista: @ViewData["Message"]
        */
        
        /*
        ViewBag
        El objeto ViewBag es un objeto de tipo dinámico (dynamic) que le permite 
        crear propiedades al vuelo.
        Uso y asignación al objetos ViewBag.Nombre = Javi
        Lectura del objeto en la vista: @ViewBag.Nombre
        */   
    }
}

MVC-NT1/Views/DerivadosActionResult/ViewResult.cshtml
@{
    ViewData["Title"] = "ViewResult";
}

<h1>@ViewData["Title"]</h1>

MVC-NT1/Views/Order/NewOrder.cshtml
@model MVC_NT1.Models.OrderViewModel

<h1>Order</h1>

<h2> @Model.Id </h2><br>
<h2> @Model.Name </h2><br>
<h2> @Model.Total </h2><br>

MVC-NT1/Views/Order/OrderList.cshtml
@model List<MVC_NT1.Models.OrderViewModel>


@{
    ViewData["Title"] = "OrderList";
}

@foreach (var item in Model)
{
    <h1>@item.Name</h1>
}

@{
    var order = new OrderViewModel {
        Id = 5, 
        Name = "10", 
        Total = 100
    };
}

<h2>El total del objeto creado es: @order.Total </h2>

@for (var i = 0; i < Model.Count(); i++)
{
    var orderTest = Model[i];
    <text>Name: @orderTest.Name</text> <br>
}

MVC-NT1/Views/Registro/RegistrarUsuario.cshtml
@model MVC_NT1.Models.UsuarioViewModel


<form asp-controller="Registro" asp-action="RegistrarUsuario" method="POST">

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Email</label>
        <input type="email" name="email" class="form-control" id="exampleFormControlInput1"
            placeholder="name@example.com">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Nombre</label>
        <input type="text" name="nombre" class="form-control" id="exampleFormControlInput1"
            placeholder="name@example.com">
    </div>
    <button type="submit">Registar usuario </button>

</form>

MVC-NT1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_NT1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_NT1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orden" asp-action="NewOrder">Crear nueva Orden</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Registro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVC_NT1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVC-NT1/Views/ViewBagYViewData/EjemploViewData.cshtml
@model MVC_NT1.Models.OrderViewModel;
@{
    ViewData["Title"] = "EjemploViewData";
}

@{
    var orderObject = ViewData["order"] as OrderViewModel;
}

<h1>View Data</h1>
<h2>@ViewData["Message"].</h2>

<h1>View Bag</h1>

<h2> @ViewBag.Nombre</h2>

<h1>Objeto view Data</h1>
<h2>@orderObject.Total</h2>


<h1>Objeto view bag</h1>
<h2>@ViewBag.Order.Total</h2>